### ISSUE TITLE
Allow newlines in info hovers

### ISSUE THREAD

**Issue by redbmk** [you-dont-need/You-Dont-Need-JavaScript#7]
I'm not sure the best way to do a pull-request with the way the demos are stored in codepen.

Adding this rule to the "Info on hover without JS" will allow the newlines to be displayed:

``` css
dfn::after {
  white-space: pre-wrap;
}
```
