### ISSUE TITLE
user-select: none;

### ISSUE THREAD

**Issue by isChenKan** [you-dont-need/You-Dont-Need-JavaScript#70]
I think add in the css code:
```css
body {
    user-select: none;
}
```
 will be better, because when I quickly click on these stuff will not appear like when the double click on the selected character style.
My English is not good enough, hope you can understand what I mean.:joy:
